#version = 1
# https://github.com/ggml-org/llama.cpp/issues/18428
[*]
n = -1

#https://unsloth.ai/docs/models/qwen3.5
[Qwen3.5-9B-InstructGeneral]
jinja = true
top-k = 20
min-p = 0.0
top-p = 0.8
temp = 0.7
ctx-size = 32768
model = /models/Qwen3.5-9B/Qwen3.5-9B-UD-Q6_K_XL.gguf
mmproj = /models/Qwen3.5-9B/mmproj-F16.gguf

#https://github.com/ggml-org/llama.cpp/discussions/15396
#https://unsloth.ai/docs/models/gpt-oss-how-to-run-and-fine-tune#running-gpt-oss
#The reasoning level can be set in the system prompts, e.g., "Reasoning: high". or Medium or Low
#https://huggingface.co/mradermacher/gpt-oss-20b-heretic-v2-i1-GGUF
#https://github.com/p-e-w/heretic
[gpt-oss-20b-heretic-v2]
jinja = true
ctx-size = 131072
flash-attn = on
ub = 2048
b = 2048
temp = 1.0
top-p = 1.0
model = /models/gpt-oss-20b-heretic-v2/gpt-oss-20b-heretic-v2.i1-MXFP4_MOE.gguf

[translategemma-12b-ENgb2DE]
jinja = true
ctx-size = 2048
chat-template-kwargs = { "source_lang_code": "en-GB","target_lang_code": "de-DE" }
model = /models/translategemma-12b-it-i1/translategemma-12b-it.i1-Q5_K_M.gguf
mmproj = /models/translategemma-12b-it-i1/mmproj-translategemma-12b-it.f16.gguf

[translategemma-12b-ENgb2RU]
jinja = true
ctx-size = 2048
chat-template-kwargs = { "source_lang_code": "en-GB","target_lang_code": "ru-RU" }
model = /models/translategemma-12b-it-i1/translategemma-12b-it.i1-Q5_K_M.gguf
mmproj = /models/translategemma-12b-it-i1/mmproj-translategemma-12b-it.f16.gguf

[translategemma-12b-DE2ENgb]
jinja = true
ctx-size = 2048
chat-template-kwargs = { "source_lang_code": "de-DE","target_lang_code": "en-GB" }
model = /models/translategemma-12b-it-i1/translategemma-12b-it.i1-Q5_K_M.gguf
mmproj = /models/translategemma-12b-it-i1/mmproj-translategemma-12b-it.f16.gguf

[translategemma-12b-DE2RU]
jinja = true
ctx-size = 2048
chat-template-kwargs = { "source_lang_code": "de-DE","target_lang_code": "ru-RU" }
model = /models/translategemma-12b-it-i1/translategemma-12b-it.i1-Q5_K_M.gguf
mmproj = /models/translategemma-12b-it-i1/mmproj-translategemma-12b-it.f16.gguf

[translategemma-12b-RU2ENgb]
jinja = true
ctx-size = 2048
chat-template-kwargs = { "source_lang_code": "ru-RU","target_lang_code": "en-GB" }
model = /models/translategemma-12b-it-i1/translategemma-12b-it.i1-Q5_K_M.gguf
mmproj = /models/translategemma-12b-it-i1/mmproj-translategemma-12b-it.f16.gguf

[translategemma-12b-RU2DE]
jinja = true
ctx-size = 2048
chat-template-kwargs = { "source_lang_code": "ru-RU","target_lang_code": "de-DE" }
model = /models/translategemma-12b-it-i1/translategemma-12b-it.i1-Q5_K_M.gguf
mmproj = /models/translategemma-12b-it-i1/mmproj-translategemma-12b-it.f16.gguf
